# Generated by Django 4.2.29 on 2026-03-07 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_publisher_role_to_editor(apps, schema_editor):
    """Map the removed publisher role to the closest remaining role."""
    UserProfile = apps.get_model("news", "UserProfile")
    UserProfile.objects.filter(role="publisher").update(role="editor")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="owner",
            new_name="created_by",
        ),
        migrations.AlterField(
            model_name="publisher",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_publishers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="receive_newsletter",
            new_name="receive_notifications",
        ),
        migrations.AddField(
            model_name="subscription",
            name="journalist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalist_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="news.publisher",
            ),
        ),
        migrations.RunPython(
            convert_publisher_role_to_editor, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(publisher__isnull=False),
                fields=("user", "publisher"),
                name="unique_reader_publisher_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(journalist__isnull=False),
                fields=("user", "journalist"),
                name="unique_reader_journalist_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        journalist__isnull=True,
                        publisher__isnull=False,
                    )
                    | models.Q(
                        journalist__isnull=False,
                        publisher__isnull=True,
                    )
                ),
                name="subscription_requires_single_target",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="news.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "article")},
            },
        ),
    ]
